server:
  port: 8081
spring:
  application:
    name: cclg.dianping
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cclg.dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null # JSON?????????
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 10s
mybatis-plus:
  type-aliases-package: com.cclg.dianping.domain # ?????
logging:
  level:
    com.cclg.dianping: debug
